config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/about'

  root 'static_pages#about'
  resources :memes do
    resources :bets, only: [:new, :create, :destroy]
  end

  devise_for :users

end

app/models/bet.rb
class Bet < ActiveRecord::Base

belongs_to :user
belongs_to :bettable, polymorphic: true

end

app/models/meme.rb
class Meme < ActiveRecord::Base

	validates_presence_of :title
	validates_uniqueness_of :url

	belongs_to :author, :class_name => "User"
	has_many :bets, as: :bettable, dependent: :destroy

	accepts_nested_attributes_for :bets, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memes, foreign_key: :author_id
  has_many :bets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# this allows user.username to be used in devise controller actions
	before_filter :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  # how the params are sanitized for the devise actions
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/bets_controller.rb
class BetsController < ApplicationController

	before_action :authenticate_user!

	def new
		@meme = Meme.find(params[:meme_id])
		if !!@meme.bets.find_by(user_id: current_user.id)
			flash[:error] = "You already bet on this!"
			redirect_to root_path
		end
		@bet = @meme.bets.new
	end

	def create
		@meme = Meme.find(params[:meme_id])
		@bet = @meme.bets.build(whitelisted_bets_params)
		@bet.user_id = current_user.id
	  if @bet.save
	  	success = ["You got a deal",
	  						 "The bet was made also, bro",
	  						 "You're on!",
	  						 "You just put your points where your internet is!"]
			flash[:success] = success[rand(4)]
			redirect_to root_path
		else
			flash[:error] = "Something went wrong, bet didn't work"
			redirect_to request.referrer
		end
	end

	def destroy
	end

	private

	def whitelisted_bets_params
		params.require(:bet).permit(:user_id, :bettable_type, :bettable_id, :initial_value)
	end

  def bettable_type
  	bettable_class.find(initial_value: params[:bets][:initial_value])
  end

  def bettable_class
  	params[:bettable].singularize.classify.constantize
  end

  def parent_id
    "#{params[:bettable].to_s}_id".downcase.to_sym
  end

end

app/controllers/memes_controller.rb
class MemesController < ApplicationController

	before_action :authenticate_user!, :except => [:show, :index]
	# add require author so people can see a list of their meme

	def index
		@memes = Meme.all
	end

	def show
		@meme = Meme.find(params[:id])
		@bets = @meme.bets
	end

	def new
		@meme = Meme.new
		@meme.bets.build
	end

	def create
		@meme = current_user.memes.build(whitelisted_meme_params)
		@bet = @meme.bets.first
		if (@meme.save && @bet.save)
			# change this to highlight the created meme
			flash[:success] = "You have created a meme!"
			redirect_to memes_path
		else
			flash[:error] = "There was a problem"
			redirect_to new_meme_path
		end
	end

	def edit
	end

	def update
	end

	private
	def whitelisted_meme_params
	  params.require(:meme).
	  	permit(:title, :url, :description, :maturation_date,
	  				 bets_attributes: [:initial_value])
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :redirect_current_user

  def about
  end

  def redirect_current_user
  	redirect_to memes_path if user_signed_in?
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper

	def bet_id_tag(meme)
		meme.id.to_s
	end

end

app/helpers/memes_helper.rb
module MemesHelper
	# thanks, viking_blogger ;)
	def form_field_error_message(resource, field_sym)
	  unless resource.errors[field_sym].empty?
	    content_tag(:span, :class => "error-message") do
	      "#{field_sym.to_s.titleize} #{resource.errors[field_sym].first}"
	    end
	  end
	end

	def meme_author(meme)
		User.find(meme.author_id).username
	end

	def minutes_ago(meme)
		((Time.zone.now - meme.created_at)/60).round
	end

	def build_link(meme)
		meme_path(meme.id)
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/bets/new.html.erb
<section id="betModal<%=@meme.id%>" class="new_bet">
  	<div class="row">
      <h4>This meme matures <%= @meme.maturation_date %></h4>
  		<div>
        <h3>How much you wanna bet?</h3>
      </div>
      <%= form_for @bet, url: meme_bets_path do |b| %>
        <div class="small-4 center columns">
          <%= b.number_field :initial_value, number: {min_max: 1..100}, required: true %>
        </div>
        <div class="actions">
          <%= b.submit "make a bet" %>
        </div>
      <% end %>
    </div>
    <%= render 'shared/errors' %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "memebet" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <% flash.each do |type, message| %>
      <div class="flash <%=type%>">
        <strong><%= type.titleize %>! <%= message %></strong>
      </div>
    <% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/memes/_meme.html.erb
<div class="meme row">
	<span class="bet_button"><%= link_to("BET »", new_meme_bet_path(meme), id: bet_id_tag(meme), data_reveal_id: 'betModal' + meme.id.to_s) %></span>
	<li>
		<strong class="bets"><%= pluralize(meme.bets.count, 'bet') %> </strong> that <%= link_to(meme.title, meme_path(meme))%> by <%= meme.maturation_date.to_formatted_s(:long) %>.
		<span class="row meme_subscript">
			first bet by <%= meme_author(meme) %>, <%= minutes_ago(meme) %> minutes ago. <%= meme.bets.sum(:initial_value) %> points on the line.
		</span>
	</li>

</div>

app/views/memes/_meme_form.html.erb
<section class="new_meme">
  <%= simple_form_for @meme do |f| %>
    <%= render 'shared/errors' %>


    <div class="row collapse">
      <div class="small-4 center columns">
        <%= f.simple_fields_for :bets do |b| %>
          <%= b.input :initial_value, number: {min_max: 1..100}, required: true %>
        <% end %>
      </div>
    </div>

    <div class="row collapse">
      <div class="maturation_date_wrapper small-12 columns">
        <%= f.input :maturation_date, as: :date,
                                start_year: Date.today.year,
                                end_year: Date.today.year + 100,
                                order: [:month, :day, :year],
                                use_short_month: true,
                                required: false %>
      </div>
    </div>

    <div class="row collapse">
      <span class="small-3 large-2 columns ">
        <%= f.label "_prediction", class: "prefix", required: false %>
      </span>
      <div class="small-9 large-10 columns">
        <%= f.text_field :title, placeholder: "Miley Cyrus will become a war bear for Putin" %>
      </div>
    </div>

    <div class="row collapse">
      <span class="small-3 large-2 columns ">
        <%= f.label "_url", class: "prefix", required: false %>
      </span>
      <div class="small-9 large-10 columns">
      <%= f.text_field :url, placeholder: "double you double you double you dot" %>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <%= f.label :reasoning, required: false %>
      </div>
      <%= form_field_error_message(@meme, :description)%>

      <%= f.text_area :description %>
    </div>

    <div class="actions">
      <%= f.submit "make a bet" %>
    </div>
  <% end %>
</section>

app/views/memes/index.html.erb
<main class="front_page">
	<section class="medium-8 small-12 medium-offset-2 columns medium-collapse bet_box">

		<ul class= "index_memes">
			<% @memes.each do |meme| %>
		  	<%= render meme %>
			<% end %>
		</ul>

	</section>
</main>

app/views/memes/new.html.erb
<%= render 'meme_form' %>

app/views/memes/show.html.erb
<div class="medium-8 small-12 medium-offset-2 columns medium-collapse bet_box">
	<%= render @meme %>
	<div>
		<span>Reasoning:</span>
		<div> <%= @meme.description %> </div>
	</div>
</div>

app/views/shared/_errors.html.erb
  <% if @meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meme.errors.count, "error") %> there is a problem!</h2>

      <ul>
      <% @meme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_header.html.erb
<h1 style="display:none;">MEMEBET</h1>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <% if user_signed_in? %>
      	<li class="active"><%= link_to("MAKEBET", new_meme_path) %></li>
      	<li><%= link_to("LOGOUT", destroy_user_session_url, {method: :delete, class: "nav_links"})%></li>
      <% else %>
      	<li class="active"><%= link_to("SIGNUP", new_user_registration_path) %> </li>
      	<li> <%= link_to("LOGIN", new_user_session_path) %></li>
      <% end %>
    </ul>
  </section>
</nav>

<header>
	<%= link_to(memes_path) do %>
		<%= image_tag "memebet.svg",
								 {"data-svg-fallback" => "#{image_path('memebet.png')}",
								 alt: "memebet",
								 class: "top_logo"} %>
  <% end %>
</header>

app/views/static_pages/about.html.erb
<main class="about">
	<%= link_to "« take me back", memes_path %>
	<!--%= image_tag("the_fuck.svg",
								{"data-svg-fallback" => "#{image_path('memebet.png')}",
								 id: "the_fuck",
								 alt: "What the fuck is this shit?"})% -->
	<h1>What the heck is this stuff?</h1>
	<div>
		<%= image_tag("memebet_about_bkg.png", class: "about_hero", alt: "memebet") %>
	</div>
	<section class="explanation">
		<p>Some folks think of memes as cute pictures of little things with text that makes them funny in that context. Other folks think of memes (and this is where the term came from) as indivisible atomic units of transmittable culture: the sociological equivalent of genes. This here is a proving ground for either meme. A battleground where hipster-dee-doodle’s digital swords may clash in a war of prediction and called-it-firstitude. You think that a song is going to be the balls in a week? Just you wait and see, no one knows about it yet - but it’s going to blow up. Yea, this is the place to make that bet.  You have to bet points on it, and if you can predict that it’s going to be a thing you get points back! Cool, huh?</p>
		<p>
		the deeper stuff is that this is going to be an archive of sorts. If everything goes well, then this will be the dynamic digital data-log of pervasive memes! Not just silly ones, but big events that actually change things. Do you think we are going to make it to mars before we destroy ourselves? That belief is a meme. Throw it up here. You get points if a bunch of people believe it, whether it’s true or not. I think it’s cool. I think it’s cool AF.</p>
	</section>
</main>